modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/TeamDiopside/Seamless/issues"
license = "All Rights Reserved"

[[mods]]
modId = "seamless"
version = "${version}"
displayName = "Seamless"
authors = "LarsMans"
description = '''
A Fabric/Forge mod that connects the outlines of Double Blocks, like Doors and Beds.
'''
logoFile = "modicon.png"

[[dependencies.seamless]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.seamless]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.seamless]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "seamless-common.mixins.json"

[[mixins]]
config = "seamless-forge.mixins.json"
